### ISSUE TITLE
Invalid argument for adjacents

### ISSUE THREAD

**Issue by BitBeep** [nfrawley93/dart_geohash#6]
Hi,
trying to use your Class, but I receive an error when trying to calculate the neighbors of an hash with any method.
It happens when the origin hash is on the borders of the map, just for example:

24.98346,-139.832302
hash: 8

81.477374,-180.0
hash: b

-82.468162, 47.026682
hash: j

The error seems to be related to the way the neighbors are calculated. That's the error:

```
Error: Invalid argument (geohash): ""
packages/dart_geohash/dart_geohash.dart 211:7                                 [_adjacent]
packages/dart_geohash/dart_geohash.dart 244:16                                [_adjacent]
packages/dart_geohash/dart_geohash.dart 269:20                                neighbors
```

Don't know how to solve this issue, can you do anything?

**Comment by nfrawley93** [comment]
There is no reason this should have taken me so long to get back to correct. I am guessing this isn't relevant to you anymore. I have corrected this issue in the newest commit 2.1.0
